### PR TITLE
Make default pagination item count and maximum item count customizable from admin ui

### PR DESCRIPTION
**Pull request by kubilaysalih**
Hello,

With this pr, the maximum number of records that API can return and the number of default records will be editable via the admin panel.

### CODE REVIEW

**Comment by ganigeorgiev** [comment]
This was requested before, but for now is left aside as the default 500 limit should be enough for most cases (_if you want to get all items at once, the SDKs comes with `getFullList()` method that will perform sequential batch requests and will return a final array with all collection records_).

Eventually sometime in the future we may introduce similar configurable limits options per collection level (could be even combined eventually with https://github.com/pocketbase/pocketbase/issues/1232).

_I appreciate the effort, but please don't file PRs for new features without previously discussing the implementation details in an issue or a Q&A discussion, to avoid spending too much time in something that may not get merged. I try to follow a specific plan/[roadmap](https://github.com/orgs/pocketbase/projects/2/views/1) and such PRs come out of nowhere, skew the initial planning and always require some tedious back-and-forth._

**Comment by kubilaysalih** [comment]
I couldn't find anything about pagination settings in roadmap, but I wanted to open pr because of [this comment](https://github.com/pocketbase/pocketbase/issues/1659#issuecomment-1399341030). 

I made such an improvement because pulling 20k or more data with the getFullList is wasted time :/

Thanks for your time.

**Comment by ganigeorgiev** [comment]
> 20k or more data with the getFullList is wasted time 

I'm not sure what is your use case, but please note that you could easily exhaust your server resources when fetching so many items at once and most of the time it would be better to batch or paginate the requests.

**Comment by kubilaysalih** [comment]
You are absolutely right, it is necessary to paginate when pulling 20k data, but I think I should have higher standards for this much data, instead of making requests that I can get 500 records all the time. Right now I can handle this in 4 or 5 requests instead of making 40 requests. I think it's possible to speed up a lot with less requests with sacrificing some resources. All I want to say is that you should leave that desicion to the user. Pocketbase is already sufficient for most scenarios. If I want to fetch 100k record in a request, its my problem, not pocketbase.

**Pull request closed without merging**
