### PR TITLE
Refactored forms/record_upsert.go, added SubmitWithoutValidation, and improved organization

### PR DESCRIPTION
**Pull request by theHamdiz**
### Pull Request: Major Refactor & Feature Additions to `forms/record_upsert.go`

Hey there, I’ve done a deep dive into the `forms/record_upsert.go` code and made a bunch of improvements. This should make the code cleaner, more maintainable, and a bit more user-friendly. Here’s what’s new:

### Changes:

1. **Code Segmentation**:
   - I’ve organized the code into clear sections: *`Types region`*, *`Public API region`*, and *`internal helper functions region`*. This makes it easier to navigate and understand where everything belongs.

2. **Fixed Typos**:
   - Went through the comments and code to fix any typos. Clear and accurate comments make life easier for everyone!

3. **New `FillWithoutValidation` Method**:
   - Added a `FillWithoutValidation` function to fill the record fields without running validation. This is super handy when you just need to populate data without the extra checks.

4. **New `SubmitWithoutValidation` Method**:
   - Added a `SubmitWithoutValidation` method that lets you submit the form without performing validation. This is particularly useful when uploading files to records that already exist and don’t need to be validated again.

5. **Simplified Regex Patterns**:
   - Cleaned up and simplified the regex patterns. Simpler patterns are easier to read, maintain, and typically perform better, I've also tested them and they are working as expected.

6. **Idiomatic Error Handling**:
   - Ensured all errors are handled in a way that’s consistent with Go best practices.(Sometimes skipped to maintain the original pocketbase expected behavior).

7. **Resource Management with Closures**:
   - Wherever resources like file handles or database connections needed to be closed, I wrapped them in closures (or lambda functions, as some might call them). This ensures they’re always properly closed, even if an error occurs.

8. **Best Practices Applied**:
   - **Separation of Concerns**: The logic is now more modular, with different concerns handled by specific functions. This makes the code easier to test and debug.
   - **DRY Principle**: Reduced repetition by moving shared logic into helper functions, making the code more concise and easier to maintain.
   - **Consistent Naming Conventions**: Used consistent naming conventions across the board, which helps avoid confusion and improves readability.
   - **Error Handling**: Every potential error is now checked and handled appropriately(Sometimes skipped to maintain the original pocketbase expected behavior), following Go’s idiomatic error-handling patterns.

Overall, these changes should make working with the `RecordUpsert` form a more pleasant experience. The code is cleaner and more organized. Plus, with the new methods, you’ve got more flexibility in how you use the form, especially when it comes to skipping validation when you don’t need it ( i.e. uploading files so there's no need to validate every field in the form's record ).

### CODE REVIEW

**Comment by theHamdiz** [comment]
BTW, I maintained the existing public API, nothing on that front changed at all, every method is the same & is there.

**Comment by ganigeorgiev** [comment]
The form is no longer used as part of https://github.com/pocketbase/pocketbase/discussions/4355.

**Comment by theHamdiz** [comment]
> If you don't want validation you can operate directly with the Dao as explained in https://pocketbase.io/docs/go-records/#create-new-record (the `Dao.SaveRecord` is roughly equivalent to direct DB insert).

I was not able to add files through multipart form data without form validation, some records are not registered with validation so in order to receive files for them I needed to populate all the missing fields which is not the responsibility of that end point, here's an example:

'''go

uploadProductImages := func(c echo.Context) error {
		// Retrieve product ID from path parameter
		productId := c.PathParam("id")

		// Find the existing record by ID
		record, err := app.Dao().FindRecordById("products", productId)
		if err != nil {
			return respondWithError(c, err, http.StatusNotFound, "Product not found.")
		}

		record.MarkAsNotNew()
		form := forms.NewRecordUpsert(app, record)

		var uploadedFileNames []string

		// Handle HeroImageFile upload and add it to the form
		heroImageFile, err := c.FormFile("hero_image_file")
		if err != nil {
			logger.LogDuringDev("%+v", err)
			return respondWithError(c, err, http.StatusInternalServerError, "Failed to open hero image file as a multipart-form-file.")
		}

		if heroImageFile != nil {
			// This should at least upload the file.
			ff, err := filesystem.NewFileFromMultipart(heroImageFile)

			err = form.AddFiles("hero_image_file", ff)
			if err != nil {
				return respondWithError(c, err, http.StatusInternalServerError, "Failed to add hero image file")
			}

			err = form.SubmitWithoutValidation()
			if err != nil {
				return respondWithError(c, err, http.StatusInternalServerError, "Could not submit the record form")
			}
			// Append the filename to the response slice
			uploadedFileNames = append(uploadedFileNames, heroImageFile.Filename)
		}

		// Return the uploaded file names as a response
		return c.JSON(http.StatusOK, map[string]interface{}{
			"message": "Images uploaded & linked successfully!",
			"files":   uploadedFileNames,
		})
	}
	
'''

Also the reddit community didn't seem to have an answer for this as well, so I think it's a real concern, am I missing something or doing something the wrong way here?

**Comment by ganigeorgiev** [comment]
@theHamdiz If you spent 2 minutes reading the [linked discussion](https://github.com/pocketbase/pocketbase/discussions/4355), and more specifically the "Remove/hide the RecordUpsert (and other similar forms)" you'll find out that the above is not needed.

> I was not able to add files through multipart form data without form validation

From the code sample from the linked discussion:

```go
// upload the file to the configured app storage
fileKey := path.Join(record.BaseFilePath(), file.Name)
fsys, _ := app.NewFilesystem()
defer fsys.Close()
fsys.UploadFile(file, fileKey)

// save the Record model field with just the uploaded file name
record.Set("fileField", file.Name)
app.Dao().SaveRecord(record)
```

> Also the reddit community didn't seem to have an answer for this as well, so I think it's a real concern

I don't maintain or care about the reddit community. Instead of opening PR without even bothering reading the [Contribution note in the readme](https://github.com/pocketbase/pocketbase?tab=readme-ov-file#contributing) it would be more helpful to open a Q&A discussion with details about your use case that has led to need the above addition.

---

I'm not posting these links to fill empty space and interested users should read them and eventually elaborate on what they disagree with.

If you are not going to read it then that's fine but you are wasting your time (and mine) in pointless back-and-forth.

If you find this unwelcoming please use something else because I'm tired and reaching my breakpoint from lazy and chatgpt-like interactions.

**Comment by theHamdiz** [comment]
> If you find this unwelcoming please use something else because I'm tired and reaching my breakpoint from lazy and chatgpt-like interactions.

Please forgive me, I am starting to learn `pocketbase` and I just want to help, kindly forgive me, is there any other way I can support the project even financially? I didn't mean to upset you.

**Comment by theHamdiz** [comment]
> @theHamdiz If you spent 2 minutes reading the [linked discussion](https://github.com/pocketbase/pocketbase/discussions/4355), and more specifically the "Remove/hide the RecordUpsert (and other similar forms)" you'll find out that the above is not needed.

Actually I have read that first thing, and it is not working, it's not only not uploading files to the filesystem, it's even not populating the field. so I thought to share this with you.

**Comment by ganigeorgiev** [comment]
This will be my last reply and I will stop engage further.

The linked discussion is about planned changes that will be available with the next v0.23.0 release soon. The title explicitly says "temporary feature freeze", meaning that new additions are not welcomed, especially when these new additions targets functionality that is explicitly mentioned that is going to be refactored.

With the next release you'll be able to do directly:

```go
record.Set("fileField", file) // just like any other regular field value (record.Get("fileField") will return a File instance)
app.Save(record) // or ~RawSave()~ SaveNoValidate() if we don't want validations
```

> Actually I have read that first thing, and it is not working

The shown code sample should work if you replace `file` with `ff` from your example (or with the [`fsys.UploadMultipart(heroImageFile, fileKey)`](https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.22.19/tools/filesystem#System.UploadMultipart).

**Pull request closed without merging**
