### PR TITLE
upgraded to aws-sdk-go-v2

### PR DESCRIPTION
**Pull request by yuxiang-gao**
This PR upgrades the S3 filesystem to use the newer version of AWS sdk (https://github.com/aws/aws-sdk-go-v2) since it was mentioned in #1343 that there is plan to do so.

### CODE REVIEW

**Comment by ganigeorgiev** [comment]
I don't want to rush it since I remember reading in the docs that the new version uses newer S3 APIs which may not be supported by all S3 providers.
It will need first to be investigated whether it works with the common S3 providers and what actually are the api changes.

**Comment by yuxiang-gao** [comment]
> It will need first to be investigated whether it works with the common S3 providers and what actually are the api changes.

That makes sense. I have only briefly tested it on three providers that I am using (AWS, Tencent COS, and MinIO) and they seems to be working. Let me know if you need any help investigating this.

**Comment by pr0ton11** [comment]
I would be up to test it with CEPH Rados Gatwway once I get it up and running. How is performance in general in S3 buckets for Pocketbase. Is it noticable?

**Comment by ganigeorgiev** [comment]
@pr0ton11 I doubt that there will be any noticable performance difference when switching from v1 to v2 of the s3 library.

If you are asking for general S3 integration performance - it depends on the internal network infrastructure of your host provider(s), the location/region of the servers, etc.

It will be definitely slower compared to a local filesystem storage.

**Review by HiteshGorana — APPROVED** [review]

**Comment by ganigeorgiev** [comment]
I've squash merged it in the `develop` branch with one minor endpoint normalization (prefixing it with `https://` if scheme is not defined; it seems that this was performed behind the scenes by v1).

I've tested it with AWS S3, DigitalOcean Spaces, Vultr Object Storage and Wasabi S3 offerings and all seems to work fine.

**Pull request closed without merging**
