### PR TITLE
Add Patreon Auth

### PR DESCRIPTION
**Pull request by ghostdevv**
I based this off the Yandex commit https://github.com/pocketbase/pocketbase/commit/435eca6f35661c91e60abae69a669aea378217aa#diff-0c7bbc200a025d45ef4358425b0a3c41b8de1e8b9d5f4b94a09f1d5c612e4481 - let me know if there is anything missing and I will add it to this pr! I tested this auth with the pocketbase js sdk and also running `make test` and `make lint`

### CODE REVIEW

**Comment by ghostdevv** [comment]
Submitted a PR to the oauth2 package to add the patreon endpoints https://github.com/golang/oauth2/pull/668

**Comment by ghostdevv** [comment]
Just thought of something - it might be worth mentioning somewhere that it requires Patreon v2

**Comment by ganigeorgiev** [comment]
Thank you! I've tested the implementation locally, with both creator and regular user/subscriber, and everything seems to work fine.

To avoid the back-and-forth, I've squash merged it directly in the `develop` branch (https://github.com/pocketbase/pocketbase/commit/71f9be3cb0d812ac982d502bee5f510cb0355c6a) (_I've added only `v2` to the provider title_).

If the Go team ended up merging the endpoints PR we can update it later, but even with the static endpoints is fine (at the end the `userApiUrl` will still be "hardcoded").

The change will be available with the next PocketBase v0.19.0 release, but please note that there are no fixed ETAs yet (_see also https://github.com/pocketbase/pocketbase/discussions/3271_). If you want to generate a static binary from the `develop` branch similar to the releases prebuilt executables, you can:

1. Checkout or clone the `develop` branch
   ```sh
   git clone https://github.com/pocketbase/pocketbase.git --branch develop --single-branch
   ```
2. Navigate to `examples/base`
3. Run `GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build` (_https://go.dev/doc/install/source#environment_)
4. Start the created executable by running `./base serve`.

**Comment by ghostdevv** [comment]
Ty!

**Pull request closed without merging**
