### PR TITLE
Custom email

### PR DESCRIPTION
**Pull request by mbecker**
The current implementation of sending emails includes only emails for internal events like "user send password reset". By using PocketBase as a framework the use case may be to send custom emails from PocketBase with the default mail client (utilising for example the SMTP connection). This implementation simplifies sending custom emails.

This implementation includes a method `SendCustomEmail(app core.App, email string, title string, template string, data any)` to send a html/template string with data to the given email address.

Additionally the hooks before / after for the event "send custom emails" are implemented as well.

Tests should be ok for the mail implementation as follows:
```sh
$go test mails/custom_test.go
ok  	command-line-arguments	0.432s

$go test ./...
ok  	github.com/pocketbase/pocketbase	1.449s
--- FAIL: TestFileDownload (0.12s)
    api.go:124: [existing image - existing thumb (zero height)] Cannot find ?PNG
        
IHDRF?Lu??IDATx??{O?:?m??k*??LZV??d?`

        NCY?Pz?=?ѩ%?
                    ??IG:?E???}?^	?/_???
                                              ?_??,ɀ?$ʒ
                                                       (K2?,ɀ?$ʒ
                                                                (K2?,ɀ?$ʒ
                                                                         (K2?,??c??b?????OB(~??i?????Sԛ???aQan?[?a???m??n????u]3???<ϲ,??j?zzz?]?B????,?0?l6B]???ϻ?.`??AP?%??m??l?f????0
           ??5????????MQ???0
                            ????m????f?N??y?TӴ??˪?nnn? 8;;;==??6">?aC???p?ׯ_?4????,?R?y^?ә?f????m???o|2?0ƾ}?999???cC5RD)}xxX??I??ah?u???Bv??v?%???k?f???u?????????߇?!?X??i??t8???????x??Ry~~N?4
?i??*?c??i??ea?W?U]?ǢA?q?M?Ea?6 ?2?3Y?QJm?v?< ??M????4??h?\.?45?4?!B(?2???8y?WU?+>I?4
                                                               ?R*ʆ?k???:?(aBȃ?EQ????l6??jը=???u???8?y??1^Q?S?XU?P?s???ģ??Z???k>??D??[b??"????n??_????β???T4å???????8??????H????ʲ?u]8?u?Rڨ+>-y(????n???j?????QJ!??	??+j?&\??^j????x~????)B?w???n??J?Ĳ,?4y)?z?<?˲<?H?????r?????????sg2?<==??ߋ
                                                                                                                 ?vm?Z\??j?4????-??n?(??⏳? ?p]W??e?j??}???cUUm??,???????8'''?٬1?!?X,??c<??EB????J?d0??<ϳ,??h4???8?????j?ۍ??0
                                                 -????!???????:c?0?ϟ?g0???D???S??g??y?sh?&Ƹ?j?u?\.?8?e?Y?5?L?0|yy???1?????oM?SQ?????(?4M;;;?7???X,??ac^)с???8?x?Vx??vz=??~????s??{???7??=D????7?_?7?$~!???k???7q?Q?d@Y?eI?%P?d@Y?eI?%P?d@Y?eI?%P?d???W??mG?tM?
        IEND?B`? in response body 
        ?PNG
        
?Y?;?eI?%P?d@Y?eI?%P?d@Y?eI?%P?d@Y?eIް?C??8??Z???????i???{?z?"B?~?!,?"
                                                                      ??v
                                                                         0
                                                                          ??v????v????kƘ?8??Y??[?VOOO??B?1v]!T?e???B?????y?????ʲض?y?mی??z?a?B#[??h0<<<???E1?L
                                                                                                                                                             ???o?????l6?t:?E?(????a?^'I??aց^???v??⺮i??^O?uBH?????????c9??M???pH???N?????RB???s??am?6M?u]B?f??????^?gYV?ӱ,??$?z?^,??P???lV???mͳU??8??,? ?,??????y^U??$IL?4
                                                                                                                                               TU?1??4M˲0ƫժ??c??8抦i???me??,?(??m;?S???w????3g??h4Z.?i??A)mï5M?u?O?0!????EQ????l6??j??=???u???8?y??1?Q?S?XU?P??9V|{?QJ[????5_?}"?x?-q?z
???/?                                                                                                      B??~??
        \__gYy?U4å???????8??????(?X???ʲ?u]8?u?R??+?-y(???n???j?????QJ!????+j?&\?6???n?????/7?0MS??(Ji??棕$?eY?i?V??zy??ey?H?????r?????????sg2?<==??ߋ
        ?qm?Z\??j?4???|,??n?(??⯃u????+??e?j??}??>cUUm??,???????8'''?٬1?!?X,??c<??EB????J?d0??<ϳ,??h4???8?????j?ۍ??0
                                                                                                                   -????!???_????:c?0??_?W0???F???K??g??}?kh?&Ƹ?j?u?\.?8?e?Y?5?L?0|yy???1?????߆?N??{9???Qi?vvv?3???X,??ac?)с????	o<??*b?^o3~?????????o??{?p?o^??o?I|!???k???7q?Q?d@Y?eI?%P?d@Y?eI?%P?d@Y?eI?%P?d????????? (??IEND?B`?
FAIL
FAIL	github.com/pocketbase/pocketbase/apis	9.657s
?   	github.com/pocketbase/pocketbase/cmd	[no test files]
ok  	github.com/pocketbase/pocketbase/core	(cached)
ok  	github.com/pocketbase/pocketbase/daos	4.505s
?   	github.com/pocketbase/pocketbase/examples/base	[no test files]
ok  	github.com/pocketbase/pocketbase/forms	15.077s
ok  	github.com/pocketbase/pocketbase/forms/validators	0.737s
ok  	github.com/pocketbase/pocketbase/mails	1.290s
?   	github.com/pocketbase/pocketbase/mails/templates	[no test files]
?   	github.com/pocketbase/pocketbase/migrations	[no test files]
?   	github.com/pocketbase/pocketbase/migrations/logs	[no test files]
ok  	github.com/pocketbase/pocketbase/models	(cached)
ok  	github.com/pocketbase/pocketbase/models/schema	(cached)
ok  	github.com/pocketbase/pocketbase/resolvers	0.454s
?   	github.com/pocketbase/pocketbase/tests	[no test files]
ok  	github.com/pocketbase/pocketbase/tokens	0.899s
ok  	github.com/pocketbase/pocketbase/tools/auth	(cached)
ok  	github.com/pocketbase/pocketbase/tools/filesystem	(cached)
ok  	github.com/pocketbase/pocketbase/tools/hook	(cached)
ok  	github.com/pocketbase/pocketbase/tools/inflector	(cached)
ok  	github.com/pocketbase/pocketbase/tools/list	(cached)
ok  	github.com/pocketbase/pocketbase/tools/mailer	(cached)
ok  	github.com/pocketbase/pocketbase/tools/migrate	(cached)
ok  	github.com/pocketbase/pocketbase/tools/rest	(cached)
ok  	github.com/pocketbase/pocketbase/tools/routine	(cached)
ok  	github.com/pocketbase/pocketbase/tools/search	(cached)
ok  	github.com/pocketbase/pocketbase/tools/security	(cached)
ok  	github.com/pocketbase/pocketbase/tools/store	(cached)
ok  	github.com/pocketbase/pocketbase/tools/subscriptions	(cached)
ok  	github.com/pocketbase/pocketbase/tools/types	(cached)
?   	github.com/pocketbase/pocketbase/ui	[no test files]
FAIL
```

I would like to think / talk / implement a way to use own mail templates for internal events in more easy way.

Hope this pull requests helps.

P.s. I had some problems with the rebase of my fork. I hope really that this pull requests only the files changed and not the rebase / branch files as well.

### CODE REVIEW

**Comment by ganigeorgiev** [comment]
Hi,thanks for the PR, but I don't think `SendCustomEmail` need to be part of the `mails` package. It doesn't do anything more than calling `app.NewMailClient().Send(...)`.

The idea of the existing mailer hooks is to override the default app behavior (aka. changing the mail template). When sending custom emails there shouldn't be a need for "custom" hooks because the core app doesn't really know anything about them (it is better to listen to changes that triggered the event, not the actual mail sending).

I'm open for discussion, so please share your use case if you disagree with the above.

_btw. Sometime in the future there are plans for "Collection triggers" which will allow sending custom email templates, configured  from the Admin UI, based on some record event._

**Comment by ganigeorgiev** [comment]
To make it a little easier constructing custom html templates, I'd consider in future release making  `mails.resolveTemplateContent` public so that it can be used in user-land code, but there is nothing wrong of having your own app helpers.

**Comment by mbecker** [comment]
Hi,

the main idea of this pull request to have a simple / standardized method in the pocketbase core to send emails with the existing mail settings and the pocketbase way to resolve html/templates. At the end it doesn't do anything more than calling  `app.NewMailClient().Send(...)`. Yes, I agree. For me it's the more convenient way that the core includes some basic features for sending mails, sending notifications, etc. with the standard core conventions.

I've implemented the hooks for "sending the custom emails" because it follows the convention of the idea of pocketbase and the code. At the end there are a lot of use cases to log / monitor all events in a production mode or there is hook listener which is implemented by a central dev team not to send spam mails. Personally, I do not have a use case for the custom hooks; I've followed the convention.

**Comment by mbecker** [comment]
> To make it a little easier constructing custom html templates, I'd consider in future release making `mails.resolveTemplateContent` public so that it can be used in user-land code, but there is nothing wrong of having your own app helpers.

Yes, a lot of the internal methods would help to use the PocketBase conventions in user-land code. That would mean to utilize existing code and not to have own code helpers. Would be great as well to have the methods in user-land code to generate / validate tokens used for example in the mails.

My use case is that signed in users are adding email addresses / mobile numbers to receive notifications. The email addresses must not be the same as for the sign in process. However, the added email addresses must be validated by a token / code.

**Comment by mbecker** [comment]
Great! Thanks! Haven't yet seen it.

**Pull request closed without merging**
