### PR TITLE
Feature/admin darkmode

### PR DESCRIPTION
**Pull request by devbyray**
# Darkmode

Since I love Pocketbase but missed the dark mode, I thought let's add it as a contribution 🙏

See the screenshot below 👇. (left is the original, right is the darkmode 😉)

I hope you guys love it as much as I do.

image

### CODE REVIEW

**Comment by ganigeorgiev** [comment]
Please check https://github.com/pocketbase/pocketbase/issues/407.

**Comment by douglaspetrin** [comment]
@devbyray Hey, to be honest, I liked what you did, at least from the image attached. Also, the changes look like they were not a big deal. Unfortunately, it was not merged.

**Comment by ganigeorgiev** [comment]
The reason it wasn't merged was explained in the linked issue. Additionally there were several other implementations before this one that covered a lot more cases than just changing the css variables (see the examples in https://github.com/pocketbase/pocketbase/issues/407 and its related closed PRs).

While I could understand that you or the author may feel unfair for not being merged I think I've been clear from the beginning that this is NOT something that I want to deal at the moment. There is even a note in the README in general for new features:

> But please refrain creating PRs for new features without previously discussing the implementation details. PocketBase has a [roadmap](https://github.com/orgs/pocketbase/projects/2) and I try to work on issues in specific order and such PRs often come in out of nowhere and skew all initial planning with tedious back-and-forth communication.
>
> Don't get upset if I close your PR, even if it is well executed and tested. This doesn't mean that it will never be merged. Later we can always refer to it and/or take pieces of your implementation when the time comes to work on the issue (don't worry you'll be credited in the release notes).

In any case, dark mode/themes support remains a low priority and I don't think this is a blocker or critical issue.

**Comment by douglaspetrin** [comment]
> The reason it wasn't merged was explained in the linked issue. Additionally there were several other implementations before this one that covered a lot more cases than just changing the css variables (see the examples in #407 and its related closed PRs).
> 
> While I could understand that you or the author may feel unfair for not being merged I think I've been clear from the beginning that this is NOT something that I want to deal at the moment. There is even a note in the README in general for new features:
> 
> > But please refrain creating PRs for new features without previously discussing the implementation details. PocketBase has a [roadmap](https://github.com/orgs/pocketbase/projects/2) and I try to work on issues in specific order and such PRs often come in out of nowhere and skew all initial planning with tedious back-and-forth communication.
> > Don't get upset if I close your PR, even if it is well executed and tested. This doesn't mean that it will never be merged. Later we can always refer to it and/or take pieces of your implementation when the time comes to work on the issue (don't worry you'll be credited in the release notes).
> 
> In any case, dark mode/themes support remains a low priority and I don't think this is a blocker or critical issue (_if it really represents a problem for you, you can try some of the extensions suggested in the linked issue_).

I understand your concerns and I also agree this is not a priority or a blocker. I am already using a plugin to "solve" that. 

@ganigeorgiev thank you for this amazing project!

**Pull request closed without merging**
