### PR TITLE
Okta Oauth2 Provider support

### PR DESCRIPTION
**Pull request by AlexGiroud**
Adding Okta Oauth2 to the providers supported.
#1675

### CODE REVIEW

**Comment by ganigeorgiev** [comment]
Thank you for working on this.

I'll review it in more details sometime later this week, but at first glance here some suggestions:

- Remove the debug print statements

- Since Okta is also a hosted service, we can set the default provider urls pointing to it and allow users to specify custom ones in the UI if they are self hosting the platform (aka. similar to the gitlab provider)

- Okta [userinfo response](https://developer.okta.com/docs/reference/api/oidc/#response-example-success-8) seems to return also a `email_verified` field that we have to map and **assign the `AuthUser.Email` only if it is `true`**.
Additionally, we can also make use of the `nickname` field and assign it to `AuthUser.Username` (_if that is what `nickname` is supposed to be; if not we can skip it_).

**Comment by AlexGiroud** [comment]
Hello @ganigeorgiev,

Thanks for the feedbacks (sorry for the debug prints)

- If i remember correctly, there is no default urls for Okta, every org has a custom one, even the test instances.
- For the userinfo, i will add the check for the email. 
- The nickname is not always provided, i can add a check (if provided -> Username, else name -> Username) 

I will try do submit the changes tomorrow

**Comment by ganigeorgiev** [comment]
After the recent comment in https://github.com/pocketbase/pocketbase/pull/1377#issuecomment-1418905209 and the recent Nextcloud app OAuth2 PR - https://github.com/pocketbase/pocketbase/pull/1821, I think it may be better to implement a generic OIDC provider (or as some users suggested to just rename the existing Authentik provider to OIDC) because the OIDC spec has list with standard [scope claims](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims) and [UserInfo fields](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) that should be the same across all OIDC providers.

I'll think a little more on it after the ongoing "View" collection type.

**Comment by AlexGiroud** [comment]
I've just tested with the authentik provider with our Okta, it's working just fine.
It a good plan 
(Could even implement the .well-known/oauth-authorization-server  to fetch the differents url reducing the number of fields to fill in the ui and an advanced toggle to fill the urls manually)

**Pull request closed without merging**
