### PR TITLE
Fix auth issue when creating new records

### PR DESCRIPTION
**Pull request by evanlurvey**
When I was trying to design a role members table for a multi tenant thing I am working on I noticed an issue where if the incoming create request had the permissions I was looking for it would allow it. 
This PR adjusts the join to use a subquery which excludes the id of the test record. 

Not sure if this is structurally where something like this should exist. I am happy to make any changes or refactors.

### CODE REVIEW

**Comment by ganigeorgiev** [comment]
@evanlurvey Could you elaborate what exactly is the issue?

The idea of the existing check inside `DrySubmit` is to verify that the transaction created record pass the Collection Create API rule.

**Comment by evanlurvey** [comment]
So say we have a query like this one 
```
@collection.tenant_member.role = "admin" && @collection.tenant_member.member = @request.user.id &&
@collection.tenant_member.tenant.id = tenant.id
```
The schema is something like this:
tenant:
  - name
tenant_member:
  - user
  - tenant
  - role
```

To me that query reads if I find an existing tenant member with the role admin, using the current request user, as long as the tenant member record I want to create matches a tenant I am an admin in then create the record. 

So with an empty database if I send a request like POST `/api/collections/tenant_member/records` with a payload of 
```
{
    "tenant": "<any tenant id>",
    "member": "<my user id>",
    "role": "admin"
} 
```
I would expect to get a permission denied if there wasn't already an existing admin role associated with my account and that tenant. But currently it will allow it. This is because when it does the dry run it actually inserts a record then does all the queries to compare. Since it was not excluding the current record we could add any qualifying data needed to make the insert happen. 

This fix simply excludes the test record that gets inserted to check permissions from the @collection query.

**Comment by ganigeorgiev** [comment]
I think there is some misunderstanding how the API rules work.

To me it doesn't make sense to add a subquery to exclude the created record - if we wanted this behavior there wouldn't be a need for a `DrySubmit` in the first place.

To be honest, I'm not sure that I understand what actually you are trying to do. The following 2 statements:
"_as long as the tenant member record I want to create matches a tenant I am an admin in then create the record_" and "_I would expect to get a permission denied if there wasn't already an existing admin role associated with my account and that tenant._" seems to contradict with each other.

`@collection.*` filter is usually intented for querying other indirect collections, aka. collections to which you don't have a direct relation field. If you apply the example `@collection.*` filter rule on the `tenant_member` it will do practically a left join with itself.

Since I'm already doing a refactoring to the users management in https://github.com/pocketbase/pocketbase/issues/376, I'll think how to "normalize" the create rule behavior because it indeed differs from the `list`, `view`, `update`, `delete` rules as mentioned in https://github.com/pocketbase/pocketbase/discussions/225#discussioncomment-3512136 (or at least to better document the nuances around it).

**Comment by evanlurvey** [comment]
I agree it could be done without the dry submit. This was a way to make it work with that mechanism. 

Without something like this in place a privilege escalation can happen with the situation given. 

I guess the same could happen by adding `@collection.tenant_member.id != id` Which would get the collection join to exclude the dry run record. 

I haven’t tested it yet. But that should do the same and could then be a documentation update instead of a code change.

**Comment by evanlurvey** [comment]
For further clarification on my scenario:

When a user wants to add someone to their tenant (assume some B2B application) I would only expect that add to go through if they were already an admin. However with the test record already “in” the collection at time of query, if the id of the test record isn’t excluded the user could create a record that makes them the admin of any tenant.

**Comment by ganigeorgiev** [comment]
> When a user wants to add someone to their tenant (assume some B2B application) I would only expect that add to go through if they were already an admin. However with the test record already “in” the collection at time of query, if the id of the test record isn’t excluded the user could create a record that makes them the admin of any tenant.

The create API rule runs after the record is "inserted" in the database, otherwise you wouldn't have access to the record fields at all. If you want to restrict the submitted user data, you could:
- use [`OnRecordBeforeCreateRequest` event hook](https://pocketbase.io/docs/event-hooks/#record-hooks) (if you are using PocketBase as framework)
- OR check the submitted request data in the rule by don't allowing role "admin" assigment, eg. `@request.data.role != 'admin'`

**Comment by ganigeorgiev** [comment]
@evanlurvey In any case, the proposed changes in https://github.com/pocketbase/pocketbase/issues/376 should simplify the users management (you will even have an options for different auth models on app level).

If you have any other ideas or suggestions how to improve the current behavior, please share your feedback in https://github.com/pocketbase/pocketbase/issues/376.

**Pull request closed without merging**
